### ISSUE TITLE
Provide simple guide for writing plugins?

### ISSUE THREAD

**Issue by zhaocai** [t9md/atom-narrow#10]
Hi, @t9md

What is your plan for this project? Do you still use it? I have some plugin ideas. Can you write a simple guide for writing plugins? Thanks.

**Comment by t9md** [comment]
I'm not actively use this for now. But will actively use if I improve, fix several bugs I already noticing.

But I'm working for different project, not available for guide you and still not get prepared as support 3rd party plugin.

If you have an idea, put on issue, welcome!

**Comment by t9md** [comment]
Close until it really get ready. It will take VERY long time I think.
At this moment, I'm not motivated to support 3rd party plugin.
Current motivation is to make pre-bundled narrow-provider really great.
