### ISSUE TITLE
Call narrow:scan from vim-mode-plus search

### ISSUE THREAD

**Issue by thancock20** [t9md/atom-narrow#116]
First, let me say thank you so much for all the work you've been putting into the narrow package. It feels like Christmas almost every time I open the editor lately.

I especially like narrow:scan as a replacement of narrow:lines, and it would be even better if it could be called from the vim-mode-plus search-input like narrow:lines can. I'm sure this will be added eventually, but since I didn't see an issue for it I thought I would add one.

Actually, I got it working on my system by adding the line:
```
'vim-mode-plus-user:narrow:scan': => @narrow('scan', uiInput: confirmSearch())
``` 
near the end of the main.coffee file.

If you'd like I can make a pull request so you don't have to worry about it.

**Comment by t9md** [comment]
Agree will introduce in next version. No need to PR. Thanks for your feedback.

**Comment by thancock20** [comment]
Sounds great, thanks.
