### ISSUE TITLE
Narrow:* error for direction: here

### ISSUE THREAD

**Issue by chenglou** [t9md/atom-narrow#12]
v0.6.0

Direction: here
Default settings

Repro:
- use narrow
- hit down key

Error:
```
Uncaught TypeError: Cannot read property 'activate' of undefined
/Users/chenglou/.atom/packages/narrow/lib/ui.coffee:19
```

**Comment by t9md** [comment]
To quickly fix, I disabled autoPreview if direction is `here`.
There might be better solution to improve ux, but I'll postpone it for more important and motivated feature enhancement for narrow.
