### ISSUE TITLE
Search for visually selected text

### ISSUE THREAD

**Issue by zenbro** [t9md/atom-narrow#129]
Is there a way to send currently selected text to one of these providers: `narrow:search-current-project`, `narrow:atom-scan`, `narrow-search`?

**Comment by t9md** [comment]
See readme scan-by-current-word like that.

**Comment by t9md** [comment]
Maybe I didn't understand your question initially.

Fist of all, there is two command for `search`

- `narrow:search`:
This **was** statically asking user for search term.
I changed this command also take selected text as search term( if empty, take input via min-editor)
This change included in next release.(v0.28.0)

- `narrow:search-by-current-word`:
This take selected text as search term, if selected text was empty, pick cursor word as search term.


This answers your question?

**Comment by zenbro** [comment]
Yes, that's great!
Thank you for this awesome tool.

**Comment by t9md** [comment]
I basically prefer `narrow:search-by-current-word`. use of `narrow:search` is rare for me.

**Comment by t9md** [comment]
If you are vim-mode-plus user, I like mapping `enter` in normal-mode to `narrow:search-by-current-word` it's very handy.
