### ISSUE TITLE
Provide better safety after accidental cmd-a + delete

### ISSUE THREAD

**Issue by chenglou** [t9md/atom-narrow#13]
Again. great plugin! =)

I have the habit of accidentally using cmd-a + delete rather than cmd-delete. The former accidentally clears the narrow pane's content and goes into a weird state. I think I override this behavior myself but I was wondering if it's worth making narrow a bit safer regarding arbitrary modifications?

Or, better idea: editing narrow's buffer, and make the change reflect in the original editor! No need to jump to place, modify, then jump back! =D

**Comment by t9md** [comment]
Yes I want evaluate inline-edit, edit-narrow-buffer-inplace-directly and save then modification reflect to actual buffer content.

So currently no motivation to protect narrow buffer, want you to use normal undo or vmp's undo(`u`) for the time being.

**Comment by chenglou** [comment]
Yep! It'd still be cool to be able to revert to the previous state though. Right now if I accidentally modify the buffer I can't undo my actions. The whole thing's stuck. That counts as a bug right?

Also, this is unrelated, but I'd like to mention that Narrow's `search-current-project` has replaced [todo-show](https://atom.io/packages/todo-show) for me. Thanks! =)

**Comment by t9md** [comment]
> Yep! It'd still be cool to be able to revert to the previous state though. Right now if I accidentally modify the buffer I can't undo my actions. The whole thing's stuck. That counts as a bug right?

I will improve that part. Maybe I'll make it un-editable like you suggested until I really implement direct-narrobufer-editing-affect-real-buffer feature.

By the way, I like `narrow:fold` then `cmd-]`, `cmd-]` to redraw with different fold level.
It's really effective when you want to grasp overall code layout quickly.

**Comment by t9md** [comment]
Tried in https://github.com/t9md/atom-narrow/pull/37
But it was difficult and give up to protect content in ideal way(auto-revert text when mutated).

Instead latest narrow support following **manual-recovery** of items in narrowEditor.
- `u` to undo vmp command since no longer have `u` custom map(u didnt work in previous version since it mapped to different command)
- `f5` or `ctrl-r`(in vmp normal mode only) to `force-refresh` which redraw narrowEditor.
