### ISSUE TITLE
README has link to old branch

### ISSUE THREAD

**Issue by Kesin11** [t9md/atom-narrow#132]
I found some links it link to "make-it-stable" branch keymap.cson in README.md
https://github.com/t9md/atom-narrow/blame/master/README.md#L289
https://github.com/t9md/atom-narrow/blame/master/README.md#L296

It seems like some commands name has already renamed in master branch.
https://github.com/t9md/atom-narrow/blob/make-it-stable/keymaps/narrow.cson#L25-L27

I did copy and paste to my keymap.cson from above, but it wasn't work correctly.
Is there any reason to link "make-it-stable" branch?

**Comment by t9md** [comment]
Oh just a mistake. Thanks. You should refer master branch. 
What part is not working by the way?

**Comment by Kesin11** [comment]
Thanks!

> What part is not working by the way?

This keymaps was not working with narrow v0.23.0
https://github.com/t9md/atom-narrow/blob/make-it-stable/keymaps/narrow.cson#L23-L27

**Comment by t9md** [comment]
but that was mistake. so refer master branch as I updated readme.
