### ISSUE TITLE
When tree-view is open, narrow-scan moves cursor into tree-view instead of Narrow UI

### ISSUE THREAD

**Issue by jonboiser** [t9md/atom-narrow#138]
When the tree view of files is open (on the left by default), my cursor is taken there when I start narrow-scan.

I then need to return control to the Narrow UI by hitting, e.g. Ctrl-0.

If the tree view is closed, the cursor is taken to the narrow UI, as expected.

Thanks!

**Comment by t9md** [comment]
Can't understand your issue.
Please describe your action step by step. and what step is unexpected behavior.

**Comment by jonboiser** [comment]
To replicate:

1. Open File in Atom
2. If Tree View is not open, open it using `cmd-\` or "Tree View: Show" command in Command Palette.
3. Use "Narrow: Scan"
4. Narrow UI (a buffer with title like `scan-1`) appears 
5. Expected: Cursor is active in `scan-1`, and typing causes scan results to be refined.
Actual: Cursor is active in the Tree View instead

6. Workaround: Use `Tree View: toggle Focus` to return control back to `scan-1`

![feb-13-2017 13-26-47](https://cloud.githubusercontent.com/assets/10248067/22897037/26d0404e-f1f0-11e6-814f-2a4716109d4e.gif)

**Comment by t9md** [comment]
Ok will check after. Are you using latest narrow?

**Comment by jonboiser** [comment]
I am using the latest.

I think it might be caused by an interaction with another plugin called Synced Sidebar https://atom.io/packages/synced-sidebar. This plugin moves the highlight in the Tree View when you move to files in your project. (but does not move cursor to tree view)

When I disable Synced Sidebar, this behavior doesn't happen.

**Comment by t9md** [comment]
Ok. Do you think this fixable by narrow side?

**Comment by jonboiser** [comment]
I'm not sure. I'll take a look at the atom-narrow code and issues at synced sidebar and let you know. For now I'll just disable synced-sidebar, since Narrow is more useful to me :+1:

**Comment by t9md** [comment]
OK, I'll check too. But as a quick impression, this seem to be issue of synced-sidebar.
Btw, are you using narrow with vim-mode-plus?
Since I'm using with vim-mode-plus, narrow without vim-mode-plus behavior is not well checked by my side.

**Comment by jonboiser** [comment]
Yes, I'm using vim-mode-plus.

**Comment by t9md** [comment]
I found this issue

https://github.com/peterdotjs/atom-synced-sidebar/issues/25

And trying to this setting seems what you want. How do you think?

<img width="504" alt="utils_coffee_ ___github_atom-narrow" src="https://cloud.githubusercontent.com/assets/155205/22897750/419bf30a-f268-11e6-8189-becc26988bb8.png">

**Comment by jonboiser** [comment]
Yes, unchecking that seems to fix this issue. Not sure if "Focus On Reveal"
ever added value for me before, so this works. Thanks!

**Comment by t9md** [comment]
OK! so close now.
