### ISSUE TITLE
Discovered a great feature: recursive narrow

### ISSUE THREAD

**Issue by chenglou** [t9md/atom-narrow#16]
Not a bug report, just a comment/Idea.

I've run `narrow: line` on an existing narrow buffer. Works as intended =D. There's some potential here!

The use-case was to narrow down on `foo` and see if there's any `bar` on the same line. I search for `foo` first then open `narrow: line` on the narrow buffer to search for `bar`, then jump and jump back to the original code).

Maybe there can be first-class support of this, or maybe it doesn't need one for now.

Also, it'd be great to see the context around a line, e.g. some shortcut to expand around the line (and heck, edit in-place!)

**Comment by t9md** [comment]
Technically possible.

But why just input `bar` on the result UI of `narow:search`  is not enough?

1. `narrow:search` for `foo`
2. input `bar` to find line which include `bar` from the `narrow:search` result.

**Comment by chenglou** [comment]
That'd work too.

I personally don't use narrow:search because I like narrow:line for its incrementality. Feels like a superset of narrow:search.

**Comment by t9md** [comment]
OK, you find matching line in the file.
So type `foo  bar` is not enough? why search 2nd `bar` in different `narrow:line` buffer?

**Comment by chenglou** [comment]
Oh, I didn't realize space was treated differently, even with fuzzy off!

Is that a desirable behavior? I think it should have searched the literal "foo bar" with fuzzy off. Then again I haven't needed searching for the literal space, yet.

I'll close this for now then; sorry for the trouble!

**Comment by t9md** [comment]
I want to remove fuzzy search for the time being.
Current status of narrow package is result of short-time-experiment, so included confusing feature without much consideration.

**Comment by chenglou** [comment]
Is it because of perf concern of useless-ness? I've turned it on and tried it a bit, then turned it off too. Fuzzy hasn't been that useful, surprisingly.

(Same for lazy-motion... I thought I'd use fuzzy more.)

**Comment by t9md** [comment]
It's counter-intuitive and even if I re-introduce fuzzy, I want postpone other more important part was polished.
What confuse normal user is when fuzzy was enabled, matching highlight was not correctly rendered. I too misunderstood `narrow:line` have bug(I've forgotten that I have enabled fuzzy).

**Comment by t9md** [comment]
> Is that a desirable behavior? I think it should have searched the literal "foo bar" with fuzzy off. Then again I haven't needed searching for the literal space, yet.

Good point, but I don't know.
I have to remember how I created and designed original narrow.
I completely step off from narrow for several months, need to re-cache the context of narrow into my brain!! 😄

**Comment by chenglou** [comment]
Yeah the highlighting was part of why I turned it off at the moment. There are probably some performance consideration for disabling it too.

Thanks for working on this, as always =).
