### ISSUE TITLE
Use rg (ripgrep) instead of ag

### ISSUE THREAD

**Issue by kompot** [t9md/atom-narrow#165]
Hi,
sorry if you've already evaluated this possibility but in my not-so-large project `ag` seems to be notably slower than `ripgrep`
https://github.com/BurntSushi/ripgrep
and seems like it might add lag and decreas smoothness of usage noticeably.

Thanks for working on on such a missing topic as project navigation in Atom.

**Comment by t9md** [comment]
Are you using this package by the way?
I want to know actial time for cmd execution and narrow execution time with sample project.
And your computer spec.

Since in my environment ag fonished within a second for big attom(big codebase) project.

**Comment by kompot** [comment]
I'm trying to use `atom-narrow`, not really grasped it, but trying and like the idea of tightly integrated navigation (btw found it via your `project-find-navigation`).

One second seems just too much, I personally think it's intolerable if you want real quick incremental suggestions (no sure that's pure `ag` problem and not just UI).

I have a maxed out MacBook Pro mid 2012 with an i7/4 cores/8 threads, 16 GB RAM and on my project for 5 simple searches `ag` usually takes 250-300 ms (and one particular search took 1,5 sec, bummer) while `rg` takes 40-50 ms. 70 ms max. Pretty big difference for me when you think about incremental search.

**Comment by t9md** [comment]
Ok diff is big, i might check if I have time thanks.
And i understand you haven't tried yet.
I will consider request, suggestion if it based on actual necessity, ux frustration.

**Comment by t9md** [comment]
I tried, evaluated, implemented to support `rg`, but for the result, as I imagined, I can say no diff from ux perspective and time measurement by performance.now
I know rg is faster than ag, but for narrow usage, ag and rg both fast enough, and rest of item rendering time is spend by the javascript world to prepare header, rendering items on atom-editor.

**Comment by kompot** [comment]
Thanks @t9md.

From my perspective there's some difference - with `rg` project search feels instant almost always but with `ag` sometimes there's a visually noticeable delay.

Also found and an issue with `rg` related to escaping. Will open a separate issue.
