### ISSUE TITLE
Setting to have narrow "toggle auto preview" on by default

### ISSUE THREAD

**Issue by chenglou** [t9md/atom-narrow#17]
I haven't found a case where I'd like auto preview to be off by default, actually. So I usually do narrow:search-current-project then toggle on auto preview myself.

The one case I can think of is when the file is too huge and you wouldn't want the toggle to be on; that's been rare for me though.

**Comment by t9md** [comment]
Sorry I cannot get your point. You want config option?

**Comment by chenglou** [comment]
Yes, sorry. I updated the description.

**Comment by t9md** [comment]
`autoPreview` is provider's option which is different by provider.

https://github.com/t9md/atom-narrow/blob/master/lib/provider/lines.coffee#L7

`narrow-ui:toggle-auto-preview` is  command to toggle default autoPreview boolean param of that provider.

What do you want?

**Comment by chenglou** [comment]
Was the toggled state supposed to persist? Because every time I open a new narrow-buffer through search-current-project, the toggle is off.

**Comment by t9md** [comment]
Currently Provider.search's default `autoPreview` value is `false`.
Provider.line 's default `autoPreview` value is `true`.
You want this to persist,  remember your `narrow-ui:toggle-auto-preview`'s effect for next narrowing?

**Comment by chenglou** [comment]
Sorry I wasn't sure whether not persisting was a bug or not, just now.

Yes. Persistence would be great. But from a UX perspective, when would you ever need to toggle it on and off on the fly? It seems that just a setting would be enough? (I don't mind either way)

**Comment by t9md** [comment]
Ok I understood  what you want, you feel all provider have default autoPreview on right?
For toggling case, whan I want to copy the part of result of narrow:line I use visual-mode of vmp, in that case autoPreview ge annoying, I believe that I was thinking at that time.

**Comment by chenglou** [comment]
Oooh I see. That makes sense. I haven't needed to do any copying so far.
Yeah, a toggle that persists across narrow buffers would be nice =).

Curious: how do you open the file whose line your cursor currently stays on, then? Do you jump to the file name itself and use `open-this`?

**Comment by t9md** [comment]
> Curious: how do you open the file whose line your cursor currently stays on, then? Do you jump to the file name itself and use open-this?

https://github.com/t9md/atom-narrow/blob/master/keymaps/main.cson#L8-L12

`enter` or `u` or `o`
