### ISSUE TITLE
Select files: multiple exclusions are allowed but not multiple inclusions

### ISSUE THREAD

**Issue by kompot** [t9md/atom-narrow#172]
Hi,
digging into narrow and was not able to find this feature.

Entering 
`aaa! bbb!`
will reduce results to those entries that do not have nor `aaa` nor `bbb`

Entering
`aaa bbb`
will reduce results to those entries that do have `aaa` AND `bbb`

This make it impossible to perform search within `aaa` and `bbb` root folder excluding everything else.

Aren't I missing anything?

If so, maybe it's better to use this logic
- all exclusions are joined with `AND` logic
- all inclusions are joined with `OR` logic
- those 2 are joined with `AND`

Also seems like both `!aaa` and `aaa!` are equal (that's weird).

**Comment by t9md** [comment]
Give me actual example query with example item list.
It's difficult to understand what you are saying impossible scenario.

**Comment by t9md** [comment]
I want discuss with example usecase and result and how that result is different from your expectation style.
So need
- example
- result
- your expectation

**Comment by t9md** [comment]
> This make it impossible to perform search within aaa and bbb root folder excluding everything else.

OK understand, your point.

**Comment by t9md** [comment]
select-files is just one of providers, so it shares [Query](https://github.com/t9md/atom-narrow/wiki/Query) characteristics with other providers.

I don't want select-files specific handling. It make learning narrow difficult.

Currently narrow query doesn't support OR expression.
If narrrow query have OR expression(e.g. `|`), input query `aaa|bbb` solve problem I think.

**Comment by kompot** [comment]
Yes, I guess adding `|` to Query would solve the problem.

**Comment by t9md** [comment]
Updated(not released)
https://github.com/t9md/atom-narrow/wiki/Query

**Comment by t9md** [comment]
released as v0.38.0.
Give me feedback if you notice anything.

**Comment by kompot** [comment]
Thanks, works great,
just one issue.

On the other thread, you said that "I want select-file preference is remembered and applied on next narrow invocation". I understand this as "when i run another search - select files query should persist". Is that right? If so, I see that it's not persisted and on every search run select files query is empty. Am I missing anything?
