### ISSUE TITLE
Ripgrep: search results are in inconsistent state when deleting 1 of 2 entries

### ISSUE THREAD

**Issue by kompot** [t9md/atom-narrow#176]
See this video — decided that's it's easier than writing it down.
There's no such bug with `ag`.

https://www.youtube.com/watch?v=_ARiorw0aM4

**Comment by t9md** [comment]
Even if video is obvious I need what point i have to focus?
It's always stressing to find out what was wrong from movie.

**Comment by t9md** [comment]
Please try to make it clear the problem with short sentences. Use movie to complement your explanation.

**Comment by kompot** [comment]
Ok, sorry, thought title of the ticket says for itself.

I've got 2 entries found (two lines containing string `1`). They are found correctly.
I do delete the first one. And both of them disappear from search results after save.
Expected behaviour — the second search result should not be removed on save.

**Comment by t9md** [comment]
What i noticed wrong is
- items are not auto refreshed
- even after manual refresh, it don't show the `1` item

**Comment by t9md** [comment]
Found reason.
because of this output format diff.

- rg doesn't add filename to each result when file to search was provided.
- This is maybe bug of `rg`, since when `vim-grep` options was provided, it should be parse-able consistent manner.

```
master github/atom-narrow% ag --vimgrep 2 hoge/sample
hoge/sample:1:1:2
hoge/sample:8:1:2
master github/atom-narrow% rg --vimgrep 2 hoge/sample
1:1:2
8:1:2
master github/atom-narrow%
```

**Comment by t9md** [comment]
v0.38.2 is out.

**Comment by t9md** [comment]
Thanks for reporting!

**Comment by t9md** [comment]
Are you a vim-mode-plus package user or not?
I just want to know who use narrow without vim-mode-plus.

**Comment by kompot** [comment]
Nope, not into vim (yet ;) regular atom user.

**Comment by t9md** [comment]
OK, thanks.
