### ISSUE TITLE
Provider specific option: "do not focus search results pane on successful search"

### ISSUE THREAD

**Issue by kompot** [t9md/atom-narrow#177]
Hi,
seems like this might be a good option to have.

My use case is the following: as of now I mostly use `scan` and `search`. And almost always perform navigation between items with prev/next shortcuts. And for me it would be more convenient to have this option set to `true` for `scan` and to `false` (default) for search.

What do you think?

**Comment by t9md** [comment]
understand, me too once have that idea.
So will try to implement it.
thanks for suggestion.

**Comment by t9md** [comment]
Released as v0.39.0

Here is my impression after tried

 - This is very experimental feature, might be removed in future( after evaluated I found I myself don't need this ).

Give me your impression, if you too don't like this feature, I'll remove( I basically don't want to manage feature I think it's unnecessary ).

**Comment by kompot** [comment]
Thanks,
actually I really like it - turned this option on not only for `scan` but for `search` and really like it so far. Probably that's just my IntelliJ IDEA past experience saying but it seems convenient. Would appreciate if you do not remove it.

**Comment by t9md** [comment]
Thanks for feedback. Understood.
Does intelliJ have similar feature?

**Comment by kompot** [comment]
Yes, their's `project search` opens search results but it's unfocused and you navigate between entries with shortcuts. Got used to it.

**Comment by t9md** [comment]
OK, understand, project search.
For me as creator of narrow, I want embrace start-narrow then quick-preview by `j` or `k` and cancel by `ctrl-g` workflow. So initially focus to narrow-editor is base, primal behavior.
But I understand your habit, custom, will keep this feature.
Thanks for suggestion, someone would have appreciate your suggestion.
