### ISSUE TITLE
Focus is switched to other/main pane when closing tab with results

### ISSUE THREAD

**Issue by kompot** [t9md/atom-narrow#179]
I observe the following:

1. Perform multiple (3) searches. This opens 3 separate tabs on the other pane.
2. Focus last of 3 tabs.
3. Close with clicking on [x] or shortcut.
4. Focus is moved to the main pane.

I expect that focus would be now on the 2nd search results pane.

**Comment by t9md** [comment]
What situaton this feature shines?
I want to know the motivation or frustration, context.

**Comment by kompot** [comment]
I do several searches, the all are in separate tabs, then I decide to close them all and after first close focus is back to the main pane that contradicts to normal tab behaviour. I guess it would be ok if `narrow`'s tabs where within some non-standard narrow interface. But they look like plain tabs but behave differently.

**Comment by kompot** [comment]
Also, some side effect that might be related to (non-standard?) tab management in narrow.

I have zen tabs installed
https://atom.io/packages/zentabs
which performs autoclosing when amount of tabs exceeds certain limit (5 is the default)

After this limit new, 6th, tab is opened, then immediately auto closed and focus is back to the main editing pane.
