### ISSUE TITLE
Feature request: add ability to select previous entries in `select-files` input

### ISSUE THREAD

**Issue by kompot** [t9md/atom-narrow#180]
Use case is the following: i've got several (2-3) rather long patterns that I use in `select-files` query. Would be great if it's possible to select previous entries with something like pressing `arrow up` in terminal.

Key map for that functionality might not be trivial as it's certainly not possible to use just `arrow up`.

What do you think?

**Comment by t9md** [comment]
What is actual patterns like? and purpose of each pattern.
Show me example.

**Comment by kompot** [comment]
I have a project which contains all parts of our system. I'm responsible for only some of the parts.
Say we have

```
/back
/front
/common
/devops
/mobile
```

Most of the time I'd like to search in `front<|mobile<|common<` only. But sometimes I also need some `devops<` searching. Would be great to easily return to previous search strings (like in standard Atom's `find-and-replace`).

**Comment by t9md** [comment]
I'll take your suggestion, will evaluate it, but wait for a weeks since I'm working on different project now, so revisiting this need some free time.

**Comment by t9md** [comment]
are you still using narrow? this will be fixed in next version.

**Comment by kompot** [comment]
Great, thanks for implementing. Actually narrow became my most frequently used atom plugin except for standard packages.

**Comment by t9md** [comment]
Oh great. Me too.
And next good news, I'll release this today.
History recall is **global** command, you can use `cmd-[`, `cmd-]` to recall history from everywere.
`cmd-e` to replace query with cursor-word.

What I want to say is these `cmd-e`, `cmd-[`, `cmd-]` is super useful, will make narrow FURTHER useful!!

**Comment by t9md** [comment]
![query-cursor-word-and-history-recall](https://cloud.githubusercontent.com/assets/155205/26302309/c4b3ffdc-3f1e-11e7-9158-c215d14d68b2.gif)

**Comment by t9md** [comment]
Released v0.43.0. Prefixed like `ctrl-cmd-[`, `ctrl-cmd-]`, `ctrl-cmd-e` to less keymap conflicts.
