### ISSUE TITLE
複数のファイルを横断するProviderを使った際にvim-mode-plusでQuery Areaに文字を入力するとnormal modeに戻る不具合

### ISSUE THREAD

**Issue by tigberd** [t9md/atom-narrow#186]
タイトルの通りの挙動でsearch, git-diff-allなどで上記挙動が発生しています。
なお1件もヒットするアイテムがなくなった場合はnormal modeに戻ることはありません。

一度vim-mode-plusとnarrow以外のプラグインを全てdisableしても発生したのでnarrowに原因があると思われます。
OSはMac OS El Capitan 10.11.6
Atomは1.16.0
各種プラグインは最新版を入れています。

軽く調べていた感じ、 `provider-base.coffee` の225行目からの
```
    pane.activate()

    atom.workspace.open(filePath, pending: true).then (editor) ->
      # Refocus to originalActivePane if necessary
      originalActivePane.activate() unless activatePane
      return editor
```
をコメントアウトした際に各種ファイルにジャンプできなくなった代わりにタイトルの挙動は発生しなくなったので別のpaneに飛んでnarrowのpaneに戻ってactivateしている際にvim-mode-plusがinsert modeからnormal modeに戻ってしまっているのではないかと思いました。

**Comment by t9md** [comment]
https://github.com/tigberd-dotfiles/dotfiles/blob/master/.atom/config.cson#L218

この設定offにしたら解決しません？
ビンゴなら narrow 自体の問題では無く vmp+narrow連携時特有のissueですね。

**Comment by tigberd** [comment]
まさにこれでした！お手数をおかけしました。

**Comment by t9md** [comment]
Close in favor of #187.
