### ISSUE TITLE
Add command to rerun last command

### ISSUE THREAD

**Issue by slavaGanzin** [t9md/atom-narrow#208]
Hello.
It would be awesome to have some command that will rerun last narrow command with previous search parameters.

**Comment by slavaGanzin** [comment]
https://github.com/t9md/atom-narrow/pull/205 I saw you already add this to roadmap ! Should I close this issue?

**Comment by t9md** [comment]
What your request? `narrow:reopen` is already provided.
Having example `ctrl-z` keymapped in README.md.
Have you tried `narrow:reopen`?

**Comment by slavaGanzin** [comment]
Damn, I miss this. Thanks!
