### ISSUE TITLE
Ability to switch off `search by double click when narrow is opened`.

### ISSUE THREAD

**Issue by kompot** [t9md/atom-narrow#217]
Right now there's a checkbox "start by double click" but there's no check box do disable searching by double click when narrow is already opened. While I think this is pretty useful but would prefer that it can be switched off as I don't want to autoupdate search results and switch context unintentionally.

**Comment by t9md** [comment]
When at least one UI was exist(workspace have narrow), dblclick is bound to query-current-word.
So you can disable it via `queryCurrentWordByDoubleClick` global setting.

**Comment by kompot** [comment]
Great, thanks, works like a charm.

It's not available in UI, right?

**Comment by t9md** [comment]
> It's not available in UI, right?
Oh, it's not intended, will check, thanks for pointing me out.

**Comment by kompot** [comment]
> What do you want to say?
Oh, is `queryCurrentWordByDoubleClick` global atom setting? I thought it's `atom-narrow` only, no?

**Comment by t9md** [comment]
Yes it's atom-narrow specific settings.
I just couldn't understand why you said 'it's not available in UI'.

**Comment by t9md** [comment]
Ok, so now cler right?

**Comment by kompot** [comment]
Yep, found it, thanks.
