### ISSUE TITLE
Search for multiple lines

### ISSUE THREAD

**Issue by bogdan0083** [t9md/atom-narrow#231]
Hi! First of all, thanks for such an amazing plugin. I use it everyday for refactoring and it's simply saving lots of time for me.

The question is: can i search for more then 1 line in Scan or Search? Let's say i want to search for these 2 tags in my project
` $screen-xs: 400px`
` $screen-sm: 767px`

Is it possible to do with narrow?

Thanks!

**Comment by t9md** [comment]
Both scan and search support regExp search option.
Enable regExp search by clicking button on control-bar then search `$screen-(xs|sm)`.

**Comment by bogdan0083** [comment]
Thank you! It makes sense. Closing
