### ISSUE TITLE
Error after typing in narrow editor.

### ISSUE THREAD

**Issue by dan-weaver** [t9md/atom-narrow#238]
Hey on version 0.50.3 I'm seeing a strange error whenever I finish typing in the narrow editor.  This console log is triggered every time: https://github.com/t9md/atom-narrow/blob/master/lib/searcher.js#L63  Are you seeing this?

Atom: 1.19.0
Narrow: 0.50.3
OSX

**Comment by t9md** [comment]
You can still use narrow or completely unusable in that version?
I don not see strange error.

**Comment by dan-weaver** [comment]
narrow search is at least unusable.. It goes away after I reinstall, then comes back soon thereafter.

**Comment by dan-weaver** [comment]
sorry I did not specify.. This only occurs with the narrow search provider it seems

**Comment by dan-weaver** [comment]
hrrrmmm.. I had some local packages linked that may have been causing this somehow.  Seems to be working after unlinking those.

**Comment by t9md** [comment]
OK.
I'm using this 0.50.x about over 1 months without problem.
Since I basically use Atom-beta.
narrow 0.50.x is rewritten to Javascript from Coffee, so I'm worried about regression introduced in rewritten process, feel free if you find any issue on this new version.

**Comment by dan-weaver** [comment]
The actual issue may not be an issue at all, but I'll let you decide.  It seems search doesn't work depending on how I open atom.  When atom  is opened from the terminal it works fine.  However I sometimes use an alfred extension (https://github.com/Cloudstek/alfred-atom) to open atom to a specific folder.  It seems this is when narrow search doesn't work.  Maybe it's not resolving `ag` properly when launched in certain contexts?  Maybe this issue is better placed in the alfred atom not sure what's going on exactly.  I'll change the title of the issue to reflect.

**Comment by t9md** [comment]
I can resolve path of `ag` or `rg` in following way of Atom launching.

 - Launch from CLI by `atom` command
 - Double click Atom application icon under `/Application` folder.

So IMO, alfred-atom should behave same way as either of above launching scenario.

How about reporting alfred-atom with
  - result of `which ag` in shell.
  - Compare `process.env.PATH` output(on chrome-dev-console) between alfred-atom launched atom vs normally-launched atom.

**Comment by dan-weaver** [comment]
yep ag is not on my path when opened with alfred.. thank you!
