### ISSUE TITLE
Check selected search engine availability

### ISSUE THREAD

**Issue by slavaGanzin** [t9md/atom-narrow#244]
I think it would be improvement if on startup selected search engine would be checked for availability in atom's PATH. 

I had no ripgrep, but selected it as search engine. Search hadn't been working while narrow hadn't showed any error notifications.

So I think on startup narrow should check ```which ${searchEngine}``` output

Can do it by myself as PR.

**Comment by t9md** [comment]
I think checking `ag` or `rg` is excecutable on `narrow:search` and throw exception if not is "OK".
Notifying error to user is enough.
As long as simple and minimum, I agree to merge it.
