### ISSUE TITLE
Excluding paths

### ISSUE THREAD

**Issue by tobiasandersen** [t9md/atom-narrow#270]
Hi, thanks for this great package! 

I work in a pretty big monorepo, but usually only open one of the packages at a time in atom. This doesn't work very well with atom-narrow, since the .gitignore file doesn't get picked up and because of that searches in e.g. node_modules, build files etc. Is there a way I can exclude certain paths some other way?

Thanks

**Comment by t9md** [comment]
I haven't tried, but `search` use `ag` or `rg` depending on your `Search.searcher` setting.

So crafting .ignore file locally will workaround issue?
https://github.com/ggreer/the_silver_searcher/wiki/Advanced-Usage

**Comment by tobiasandersen** [comment]
Oh got it, worked perfectly. Thanks!
