### ISSUE TITLE
Update multiple real files in `atom-scan` not working

### ISSUE THREAD

**Issue by asyncerror** [t9md/atom-narrow#284]
In Atom Scan the feature Update Real File is expected to work in multiple files? Here the files are not updating after using the command ``Narrow Ui: Update Real File``.

![narrow-multiple-files](https://user-images.githubusercontent.com/324835/36504383-172b11b8-172f-11e8-8615-6cac7b781bec.png)

*OFF-TOPIC
We talked by email earlier and you introduced me to Narrow.
I'm getting used to it, this is a killer package, thank you.

**Comment by t9md** [comment]
> In Atom Scan the feature Update Real File is expected to work in multiple files?

Yes it should. 
And this is BUG. will fix soon.
Thanks for catching this. I normally use `search` than `atom-scan`.
If you can install `ag`(silversearcher) or `rg`, `search` is faster than `atom-scan`.

> *OFF-TOPIC
> We talked by email earlier and you introduced me to Narrow.
> I'm getting used to it, this is a killer package, thank you.

I remember from your avatar icon.
Thank you trying this pkg, this pkg is as important as vmp for me.

**Comment by t9md** [comment]
Correction: This was not BUG, I've forgotten that I removed this feature from `atom-scan` **intentionally** to avoid dangerous partial update-file happens.

https://github.com/t9md/atom-narrow/commit/d1f541691f60fa8460a7a24efe51f3d3a85559e6

So what I will do from now is to re-think the way how to support directEdit for `atom-scan` provider.

**Comment by t9md** [comment]
Try just released v0.62.0. if you still use `atom-scan`!
(But basically I recommend to use `search` for perf)

**Comment by asyncerror** [comment]
It's working!
I installed `ag` and tested it on a case with 5K + files, the speed is impressive.
Good learning here. Thanks!
