### ISSUE TITLE
[Feature Request] Search provider. AG. Follow symlink options

### ISSUE THREAD

**Issue by ocoka** [t9md/atom-narrow#293]
Hello, it can be very convenient for some project to have follow symlink settings in *narrow* or *search provider*, or add ability to pass options to *AG* itself.

**Comment by t9md** [comment]
What option do you want to pass to ag?
Once this plg supported direct pass-theouth option configuration but I removed.
I thin what you want to do is directly specify options to ag.
Am I understanding your request correctly?

**Comment by ocoka** [comment]
Yes, I just want to **ag** to follow symbolic link (so its **-f** option)

**Comment by t9md** [comment]
try v0.65.0.

You need to manually set extra CLI args.
From narrow's setting, find `Ag Extra Args` from `Search` setting.

<img width="785" alt="settings_ ___github_atom-narrow" src="https://user-images.githubusercontent.com/155205/37448028-f75b368e-2867-11e8-9932-985565a4e818.png">

**Comment by ocoka** [comment]
thanks will try now

2018-03-15 9:47 GMT+03:00 t9md <notifications@github.com>:
