### ISSUE TITLE
cursor shouldn't move when editing search query

### ISSUE THREAD

**Issue by dwelle** [t9md/atom-narrow#297]
When editing the search query in narrow search provider, cursor is always moved at the end of query when search executes:

![narrow_cursor_change](https://user-images.githubusercontent.com/5153846/39815866-ab384668-5399-11e8-92ed-3275ddcd8695.gif)

This makes editing query very annoying.

Narrow `0.65.0`, Win7, Atom `1.26.1`

**Comment by dwelle** [comment]
related https://github.com/t9md/atom-narrow/issues/257

**Comment by t9md** [comment]
@dwelle you are right, #257 have very similar issue and technically fixable by same approach I did to solve this issue.
But I need to give more careful, thorough thinking to it, since it breaks several assumptions I had when creating this package. So treat it separately.

**Comment by t9md** [comment]
For clarification issue you reported originally was fixed in the commit above, will be released in next version.

**Comment by t9md** [comment]
released as v0.65.1 jus now.
