### ISSUE TITLE
narrow:focus should put cursor on UI's active line

### ISSUE THREAD

**Issue by dwelle** [t9md/atom-narrow#299]
When executing `narrow:focus` command while narrow UI is focused, it gives focus back to editor pane (which is correct), but the cursor IMO should point to the active line that is focused in UI (currently the cursor in the editor is left at the last position it was at before the UI was focused).

Narrow `0.65.0`, Win7, Atom `1.26.1`

---

Workarounds:
- disable `close on confirm`, and use `enter` to focus editor at given line.
- use `Narrow Ui: Confirm Keep Open` command. Can be mapped to the same key as `narrow:focus`:

    ```
    'atom-workspace.has-narrow atom-text-editor':
        'ctrl-alt-/': 'narrow:focus'

    'atom-text-editor.narrow.narrow-editor.read-only:not(.vim-mode-plus)[data-grammar="source narrow"]':
        'ctrl-alt-/': 'narrow-ui:confirm-keep-open'
    ```

**Comment by t9md** [comment]
In my terminology

- `narrow:focus` just switch focus of active pane-item without **confirming**.
- If user want to jump to currently selected item, user need to **confirm** by `core:confirm` or `narrow-ui:confirm-keep-open` as you explained.

Although I do nothing to solve this issue, the workarounds you put above would be help for other user I think, thanks!
