### ISSUE TITLE
No focus in editor after confirming selection in narrow

### ISSUE THREAD

**Issue by averrin** [t9md/atom-narrow#30]
When i select narrow line focus not in work-pane

**Comment by t9md** [comment]
Maybe because of this bug?
https://github.com/atom/atom/issues/13206#event-887744695

**Comment by averrin** [comment]
yeah, i think it is it.

**Comment by t9md** [comment]
Ok we will have to wait upstream release.

Btw if you try other plugin I created, this might gives you a hint.

https://github.com/t9md/atom-vim-mode-plus/issues/486

**Comment by averrin** [comment]
I use it from very early versions=)

**Comment by t9md** [comment]
Oh thanks! But the link is not for vmp, it's describing the status of each packages Im maintaining.
The quarity varies depending on my motivation.
The package I can assuere the quality is the package I realy use in daily basis. E.g. Cursor-history, vim-mode-plus, quick-highlight, project-folder etc

**Comment by averrin** [comment]
So, i periodically check your repos for new plugins=) I have installed ~7 plugins, and use every day 4-5 of this

**Comment by t9md** [comment]
Oh, that's encourage me a lot!!
How about project-folder? I like this very much.
Some of my package I dont like current code base but I like this some of it.

**Comment by averrin** [comment]
Used it on former workplace, where we had many modules in separate repos. But yes, its cool. I love all "keyboard-only users" plugins and hate atom for ugly navigation in setting and focus bugs like this.

**Comment by usirin** [comment]
Is there an easy workaround for this until a new release comes up? It becomes increasingly annoying each time it happens.

**Comment by t9md** [comment]
The for the linked issue is already included in latest beta release now, update it then restart.
If still not fixed its narrow's bug.

I can't check at this time.

**Comment by t9md** [comment]
Checked, Not happens in latest beta

```
$ atom-beta  --version
Atom    : 1.13.0-beta8
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```
