### ISSUE TITLE
Don't make files update if "Update real file" dialog options

### ISSUE THREAD

**Issue by ocoka** [t9md/atom-narrow#311]
On latest Atom update files feature broken when "Confirm on update real file" option checked. I think some API changes occurs in Atom for dialog result code.

**Comment by ocoka** [comment]
On Linux

**Comment by heftyfunseeker** [comment]
fix for this here: https://github.com/t9md/atom-narrow/pull/312

**Comment by t9md** [comment]
I have published v0.65.2 now. Thank you @heftyfunseeker!
