### ISSUE TITLE
Deprecated selector in `narrow/styles/main.less`

### ISSUE THREAD

**Issue by usirin** [t9md/atom-narrow#32]
In `narrow/styles/main.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow .narrow-ui-row` => `atom-text-editor.editor .narrow-ui-row`

* `atom-text-editor .narrow-match .region,
atom-text-editor::shadow .narrow-match .region` => `atom-text-editor .narrow-match .region,
atom-text-editor.editor .narrow-match .region`

* `atom-text-editor .narrow-flash .region,
atom-text-editor::shadow .narrow-flash .region` => `atom-text-editor .narrow-flash .region,
atom-text-editor.editor .narrow-flash .region`

* `atom-text-editor .narrow-result .region,
atom-text-editor::shadow .narrow-result .region` => `atom-text-editor .narrow-result .region,
atom-text-editor.editor .narrow-result .region`

* `atom-text-editor .line.narrow-result,
atom-text-editor::shadow .line.narrow-result` => `atom-text-editor .line.narrow-result,
atom-text-editor.editor .line.narrow-result`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by usirin** [comment]
This is from Deprecation Cop.

**Comment by t9md** [comment]
OK  I know I just postponed to working on this will fix soon.
Thanks for reporting.

**Comment by usirin** [comment]
I don't mind sending a PR to fix this. It might take a while for me though; I just switched to atom for full time from neovim yesterday :)

**Comment by t9md** [comment]
oh, then you tried vim-mode-plus?
My main focus is always vim-mode-plus, I have lot of idea for narrow itself but tend to postpone it since my backlog of vmp is always full.

**Comment by t9md** [comment]
If you are now finding/evaluating several packages.
Here might give you a hint, state of packages I'm maintaining.

https://github.com/t9md/atom-vim-mode-plus/issues/486

**Comment by usirin** [comment]
yeah, vmp is the reason i felt comfortable for the full switch yesterday.

The editing experience has so far been really awesome, and i think even better than real vim with the changes you made to the cursor positions (i mean the opinionated new defaults) after operations.

I have made a full switch like ~5 months ago to neovim from original vim, but i got tired of the limits of the terminal/text-based layouts, because of the fact that as a web developer myself know that dom could be much easier. And we are using coffeescript in my company as well, so it makes `atom` the best place for me to get to the hacking side of the editors. I've been obsessed with them lately :) 

> If you are now finding/evaluating several packages.
> Here might give you a hint, state of packages I'm maintaining.

> t9md/atom-vim-mode-plus#486

That's how I ended up started to use narrow already, as `unite.vim` is part of my main neovim workflow, i'd rather have a good replacement for it. 

Also I tend to use packages from the same author as much as possible because of the fact that they are actually sharing the same api, but with different command name spaces. So, I'll probably check out all of your packages, since I really admire what you are doing with wpm -not implementing the wheel whereas pretty much all the other modes try to do not only with atom but with every kind of platform tries to emulate every vim feature. But rather give the experience, so kudos for that.

> My main focus is always vim-mode-plus, I have lot of idea for narrow itself but tend to postpone it since my backlog of vmp is always full.

I think this is one thing i can try to help, if you can show me some pointers on code, i would like to get a try to create my first atom package as a `narrow-source`.

**Comment by t9md** [comment]
You use Atom-beta? My vmp release is targeting atom-beta at this point.
So If you use Atom-stable, using Atom-beta greatly improve vmp more.
But I won't recommend Atom-beta in your workplace development, it tend to buggy especially in early stage.

This time change from current stable Atom-1.12 to Atom-1.13(now in beta) is very big because it [remove ShadowDOM](http://blog.atom.io/2016/11/14/removing-shadow-dom-boundary-from-text-editor-elements.html).

This narrow warning is because of this, but careful understanding of Atom history.
So will do it by myself(thanks for suggesting to help me out).
Fix is very easy at coding-level, but I can postpone till Atom 1.13 will stable(will happens soon I believe).

**Comment by usirin** [comment]
> You use Atom-beta? My vmp release is targeting atom-beta at this point.

Yep. So far so good with 1.13.

> This narrow warning is because of this, but careful understanding of Atom history.
So will do it by myself(thanks for suggesting to help me out).
Fix is very easy at coding-level, but I can postpone till Atom 1.13 will stable(will happens soon I believe).

No worries. I am happy to help whenever it is needed.
