### ISSUE TITLE
[help!] Narrow Search returns nothing and `ag` hangs

### ISSUE THREAD

**Issue by zhaocai** [t9md/atom-narrow#9]
After I start a `narrow-search` or `narrow-search-current-project`, a empty pane named `search` is opened, then nothing. Check the system, the `ag` process is there and never exit itself. Do you have any suggestion to debug this issue? Thanks.

**Comment by t9md** [comment]
Humm, maybe I need special care for windows? not sure.
Is that happen always you did `narrow:search` or happen occasionally?

**Comment by Allegathor** [comment]
Hello. I have the same issue as zhaocai. It happens every time I'm trying to perform `narrow: search`.

**Comment by t9md** [comment]
You use windows?

**Comment by Allegathor** [comment]
Yes, win 10. Ag works correctly in terminal(cmder).

**Comment by t9md** [comment]
- I released tryout-fix for this issue.
- Can some windows user try this version work?

`apm install narrow@0.10.1`

**Comment by Allegathor** [comment]
Still nothing (just empty pane). But I have checked atom-fuzzy-grep plugin, it use ag for a search by default and works properly.  Also I have found that fuzzy-grep had the same [issue](https://github.com/geksilla/atom-fuzzy-grep/pull/24) with win. Maybe it should help?

**Comment by t9md** [comment]
My change for 0.10.1 is borrowed from atom-fuzzy-grep.
Did you tried narrow 0.10.1 and restart Atom then still not worked?

**Comment by t9md** [comment]
Oh but I didn't read the issue you pasted. Thanks ,it is very similar so will read cafrefully.

**Comment by t9md** [comment]
Humm, i read that PR and found it's fix is exactly same I introduced in narrow 0.10.1.
So want to make sure if 0.10.1 is really not working for windows.

**Comment by Allegathor** [comment]
Yes, I've noticed that fix is exactly the same, but have no idea why search doesn't work in narrow. I have tried `narrow:search` with 0.10.1 several times and it doesn't work.

**Comment by t9md** [comment]
OK thanks for checking again!!
Will check that issue again.
My environment is Mac and have no Windows machine.
So hope someone further narrow down the issue.
Maybe I can create small code snippet just output of ag to console.log to find out minimum working code.

**Comment by t9md** [comment]
Still my narrow is NOT exactly same option with fuzzy-grep, so we have chance.

**Comment by Allegathor** [comment]
Hello. Didn't use Atom for some time. In current version of narrow all commands works as expected on windows 10. I think you can close the issue.

**Comment by t9md** [comment]
Wow!! I was waiting for the feedback from windows user like this!!

Thans!!
