### ISSUE TITLE
[help!] sometime calling editor get blank after open narrow-editor

### ISSUE THREAD

**Issue by t9md** [t9md/atom-narrow#95]
I don't know how to repro. Please tel me if someone find out "how to repro".

just open `narrow:line` on `right` side pane make blank original(narrow invoked) editor.

**Comment by t9md** [comment]
Not 100% sure for this fix, will re-open if I see it again.

**Comment by t9md** [comment]
Still happens frequently, want to fix this really!

**Comment by t9md** [comment]
@thancock20  Do you hit this issue?

This is occasional issue. when start narrow, original editor(narrow invoking editor) get blank after narrow opened, items in narrow-editor's are rendered correctly event in this happens.

Have you ever hit this issue?

**Comment by thancock20** [comment]
I have had that happen a couple times, but not too often. I have no idea how to repro it though.

**Comment by t9md** [comment]
Thanks, worth to know it's not my env specific.

**Comment by t9md** [comment]
This is same issue

https://github.com/atom/atom/issues/12081

I hit this issue by simply invoke `pane:split-down-and-copy-active-item`.
So this is not `narrow` specific issue.
But I tend to more frequently hit this issue since then I started to use narrow, but this is not directly means narrow code have some issue, since using narrow itself means "more frequent pane-split than ever" that might reason I feels hitting this issue rate increased.

**Comment by t9md** [comment]
Some progress,

- I though it somehwat related to `vim-mode` or `vim-mode-plus`, but it wasn't.
- Without `vim-mode` or `vim-mode-plus` I could reproduce.
- I think this is kind of bug of upstream atom-core( or underlying text-buffer ).
- But `narrow` code make this issue more likely to happen.

# Reproduce

I can 100% reproduce in following step :tada:

1. Ensure there is single pane on workspace( not happens in two pane layout ).
2. `narrow:search-by-current-word` for some word which find multiple item.
3. move cursor on `narrow-editor` and preview for **different-file-item**.
4. `ctrl-g` to `narrow:cancel`. `narrow-editor` closed, now focused on original editor, cursor position.
5. Invoke `narrow:search-by-current-word` with same word( since you cancelled , didn't move cursor position )
6. Editor become blank. clicking it throw exception ` Invalid Point: (NaN, 0)`.


![narrow-editor-blank-issue](https://cloud.githubusercontent.com/assets/155205/23742476/4af23e2e-04f0-11e7-9730-57307ca0114a.gif)

**Comment by t9md** [comment]
issue happens, only by split pane by pane-split (e.g. `pane:split-up` ) on step 5.

**Comment by t9md** [comment]
@brumm released v0.37.1. this issue is fixed.
